# Generated by Django 5.0.4 on 2024-05-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NhanVien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_nhan_vien", models.CharField(max_length=10, unique=True)),
                ("ho_ten_nhan_vien", models.CharField(max_length=100)),
                ("luong_co_ban", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "loai_nhan_vien",
                    models.CharField(
                        choices=[
                            ("vanphong", "Nhân viên văn phòng"),
                            ("kinhdoanh", "Nhân viên kinh doanh"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "luong_hang_thang",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "db_table": "tbl_nhavien",
            },
        ),
    ]
