# Generated by Django 5.0.4 on 2024-05-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qlnv", "0002_alter_nhanvien_loai_nhan_vien"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nhanvien",
            name="luong_co_ban",
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="luong_hang_thang",
            field=models.IntegerField(max_length=100),
        ),
    ]
