# Generated by Django 5.0.4 on 2024-05-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qlnv", "0003_alter_nhanvien_luong_co_ban_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nhanvien",
            name="luong_co_ban",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="nhanvien",
            name="luong_hang_thang",
            field=models.IntegerField(),
        ),
    ]
